### PR TITLE
Add some links to the sidebar

### PR DESCRIPTION
**Pull request by stevage**

### CODE REVIEW

**Comment by rufuspollock** [comment]
@stevage I wonder if these should go to the footer - the sidebar is getting quite crowded. wdyt?

**Comment by stevage** [comment]
Ah, you think it's crowded? To me it's lonely and incomplete...

To explain my motivation, I work infrequently on OS stuff. I come to http://community.openspending.org/next/ and try to remember where all the bits are so I can refresh my memory and add some value somewhere. Mostly the things I'm looking for are the code, proposals under discussion, and the current version of the architecture.

If you want to trim down the side bar, you might consider that the Tech Hangouts and Presentation links are kind of static content, so (IMHO) not something a returning participant likely needs to access more than once.

Also if space is an issue, I guess we could link the Github pages for the OSEPs under the OSEPs item...but really I think it makes sense to have actual code outputs as a top level menu item.

**Comment by rufuspollock** [comment]
@stevage actually i think i misunderstood the pull. Could you resubmit to fix conflicts and we try to get it in.

**Comment by stevage** [comment]
OK @rgrp, have another look.

**Comment by rufuspollock** [comment]
thanks - looks great.

**Pull request merged**
