### PR TITLE
fix title/logo breaks on small screan #44

### PR DESCRIPTION
**Pull request by hoony-o-1**
please let me know something to rewrite if there is

### CODE REVIEW

**Comment by danfowler** [comment]
Sorry, but I still see this happening.

screen shot 2015-12-04 at 17 37 29

**Comment by hoony-o-1** [comment]
that was on my purpose. I thought that just one line on small screen is quite not good. ok I'll fix it if I have to :space_invader:

**Comment by hoony-o-1** [comment]
I've updated :)

**Comment by danfowler** [comment]
Neat!  I will review.  Thanks for your all your work so far!  :)

**Comment by danfowler** [comment]
I really like this.  Thanks for your efforts!  It solves the problem, but my only hesitation is that the text is smaller on a full-size screen as well as on a smaller screen.  Is there a way to only make the text smaller on a small screen?

**Comment by hoony-o-1** [comment]
oh i'm sorry that there was a small mistake. I've fixed and pushed. thanks!

**Comment by danfowler** [comment]
Merging.  Thanks, @hoony!

**Comment by hoony-o-1** [comment]
great! :+1: :space_invader:

**Pull request merged**
